STACKS  SEGMENT   STACK     ;堆栈段
      DW  128 DUP(?)  ;注意这里只有128个字节
STACKS  ENDS

DATAS  SEGMENT
     STRING  DB  13,10,'Hello World!',13,10,'$'
DATAS  ENDS

CODES  SEGMENT
     ASSUME    CS:CODES,DS:DATAS
START:
     MOV  AX,DATAS
     MOV  DS,AX
     LEA  DX,STRING
     MOV  AH,9
     INT  21H
   
     MOV  AH,4CH
     INT  21H
CODES  ENDS
    END   START